//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProfile
    {
        public int TblProfile1 { get; set; }
        public string TblName { get; set; }
        public Nullable<System.DateTime> TbleBirth { get; set; }
        public string TblAddress { get; set; }
        public string TblMail { get; set; }
        public string TblPhone { get; set; }
    }
}
